### ISSUE TITLE
Meeting point

### ISSUE THREAD

**Issue by gortazar** [edugithub/jenkins-job-failure-magnifier#1]
Si ves este issue es que estamos en el mismo barco :) Contesta para saber que has llegado hasta aquí.

**Comment by edugithub** [comment]
Hola Patxi, estoy escribiendo desde zube.io. Que ya veo que está conectado al repo

**Comment by gortazar** [comment]
Ok, mándame un correo para que tenga tu correo electrónico y te invite a slack. Por ahí nos podemos comunicar más ágilmente y os puedo notificar cosas importantes sobre el tfg.

**Comment by edugithub** [comment]
Ok, acabo de enviarte un mail.
